<?php $this->renderPartial('_form',
    array(
        'model'=>$model,
        'catChild'=>$catChild,
        'idCat' => $idCat,
        'city'=>$city,
        'district' => $district,
        'microdistrict' => $microdistrict,
        'transaction'=>$transaction,
        'houseType'=>$houseType,
        'countRooms'=>$countRooms,
        'contact'=>$contact,
        'wall_material'=>$wall_material,
        'distance_to_town'=>$distance_to_town,
        'location' => $location,
        'deadlineRent' => $deadlineRent,
        'classroom_building' => $classroom_building,
        'protection' => $protection,
        'type_garage' => $type_garage,
        'timer_ads' => $timer_ads,
        'timeInterval' => $timeInterval,
        'brend' => $brend,
        'avto' => $avto,

    )); ?>